# https://huggingface.co/baidu/ERNIE-4.5-21B-A3B-PT
# https://novita.ai/models/model-detail/baidu-ernie-4.5-21B-a3b
name = "ERNIE 4.5 21B A3B"
description = "Open ERNIE text MoE with 21B total and 3B active parameters"
family = "ernie"
release_date = "2025-06-30"
last_updated = "2025-06-30"
attachment = false
reasoning = false
tool_call = true
temperature = true
open_weights = true
license = "Apache-2.0"

[limit]
context = 131_072
output = 8_000

[modalities]
input = ["text"]
output = ["text"]

[[weights]]
label = "Hugging Face"
url = "https://huggingface.co/baidu/ERNIE-4.5-21B-A3B-PT"
