base_model = "alibaba/qwen3.5-flash"

[[reasoning_options]]
type = "toggle"

[[reasoning_options]]
type = "budget_tokens"
min = 1
max = 81_920

[cost]
input = 0.09
output = 0.368
cache_read = 0.09

[limit]
output = 32_768
