# https://novita.ai/models/model-detail/meta-llama-llama-3.1-8b-instruct
base_model = "meta/llama-3.1-8b-instruct"
structured_output = true

[cost]
input = 0.02
output = 0.05

[limit]
context = 16_384
output = 16_384
