# https://novita.ai/models/model-detail/meta-llama-llama-4-maverick-17b-128e-instruct-fp8
base_model = "meta/llama-4-maverick-17b-instruct"
structured_output = true

[cost]
input = 0.27
output = 0.85

[limit]
context = 1_048_576
output = 8_192
