# https://novita.ai/models/model-detail/meta-llama-llama-3.3-70b-instruct
base_model = "meta/llama-3.3-70b-instruct"
structured_output = true

[cost]
input = 0.135
output = 0.4

[limit]
context = 12_288
output = 12_288
