# https://commandcode.ai/models/glm-5-3
base_model = "zhipuai/glm-5.3"

[[reasoning_options]]
type = "effort"
values = ["low", "high", "max"]

[interleaved]
field = "reasoning_content"

[cost]
cache_read = 0.26
input = 1.4
output = 4.4
