# https://huggingface.co/Qwen/Qwen3-Reranker-8B
# https://qwenlm.github.io/blog/qwen3-embedding/
name = "Qwen3 Reranker 8B"
description = "Multilingual query-document reranking model supporting more than 100 languages"
type = "reranking"
family = "qwen"
release_date = "2025-06-05"
last_updated = "2025-06-05"
attachment = false
reasoning = false
tool_call = false
temperature = false
open_weights = true
license = "Apache-2.0"

[limit]
context = 32_768
output = 0

[modalities]
input = ["text"]
output = ["text"]

[[weights]]
label = "Hugging Face"
url = "https://huggingface.co/Qwen/Qwen3-Reranker-8B"
