base_model = "zhipuai/glm-5.3"
name = "GLM 5.3 Fast (SCX.ai)"
reasoning = false
tool_call = false
structured_output = false

[cost]
input = 2.8
output = 8.8
cache_read = 0.56

[limit]
output = 128_000
