# https://commandcode.ai/models/qwen3-7-max
# Toggle: enable_thinking true|false
# Budget: thinking_budget
base_model = "alibaba/qwen3.7-max"

[[reasoning_options]]
type = "toggle"

[[reasoning_options]]
type = "budget_tokens"

[cost]
cache_read = 0.5
cache_write = 3.13
input = 2.5
output = 7.5
