# https://commandcode.ai/models/qwen3-6-max-preview
# Toggle: enable_thinking true|false
# Budget: thinking_budget
base_model = "alibaba/qwen3.6-max-preview"

[[reasoning_options]]
type = "toggle"

[[reasoning_options]]
type = "budget_tokens"

[cost]
cache_read = 0.26
cache_write = 1.63
input = 1.3
output = 7.8
