# https://commandcode.ai/models/kimi-k2-7-code-highspeed
base_model = "moonshotai/kimi-k2.7-code-highspeed"
reasoning_options = []

[interleaved]
field = "reasoning_content"

[cost]
cache_read = 0.38
input = 1.9
output = 8
