# Toggle: reasoning.enabled = true|false
# https://openrouter.ai/docs/guides/best-practices/reasoning-tokens
base_model = "deepseek/deepseek-v4-flash"

[interleaved]
field = "reasoning_content"

[[reasoning_options]]
type = "toggle"

[[reasoning_options]]
type = "effort"
values = ["high", "xhigh"]

[cost]
input = 0.07784
output = 0.15568
cache_read = 0.015568

[limit]
context = 1_048_576
