# Toggle: reasoning.enabled = true|false
# https://openrouter.ai/docs/guides/best-practices/reasoning-tokens
base_model = "deepseek/deepseek-v4-pro"

[interleaved]
field = "reasoning_content"

[[reasoning_options]]
type = "toggle"

[[reasoning_options]]
type = "effort"
values = ["high", "xhigh"]

[cost]
input = 0.91089
output = 1.82178
cache_read = 0.075908

[limit]
context = 1_048_576
